services:
    mariadb:
        image: mariadb:latest
        container_name: rgb-ripper-db
        ports:
            - "127.0.0.1:3306:3306"
        env_file:
            - ./.env.docker.mariadb
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./.cache:/var/lib/mysql
        restart: always